### ISSUE TITLE
error/concurrentviewing

### ISSUE THREAD

**Issue by rockers961** [benaranguren/nuodtayo.tv#2]
Hi, I guess there is an issue now on viewing TFC on multiple devices at the same time?

**Comment by ricardobothe** [comment]
Hi rockers961,
I cannot confirm this at the moment having issues viewing TFC on multiple devices at the same time.  I will try and let you know.  
Nevertheless, since yesterday 19 Jun (around 2pm GMT) all Drama/Shows/News (i.e. Love to last, Wildflower, etc..) can only be viewed for 2minutes  using version 0.1.7.   Having this encountered I deinstalled 0.1.7 and re-installed teh previous version like 0.1.5 and to my surprise and it worked.

@benaranguren,  thanks a lot (and we really appreciate it very much)  for your time and efforts in solving all this issues.   In case you will be able and find time to look at this issue, just to narrow down your investigation..  In order to fix the problem I mentioned above I de-installed  0.1.7  and re-installed (in my case) version 0.1.5.  I cannot confirm now if  0.1.6 works as I only had version 0.1.5 available :).   If I have time in the late afternoon (once at home) I will test 0.1.6 and let you know.

cheers,
Ricardo

**Comment by rockers961** [comment]
Hi, appreciate all the efforts :) clearing KODI's cache solve the 2 minute playing issue for me, and it also fix playing tfc on multiple devices too. Thank you so much

**Comment by ricardobothe** [comment]
Hi Rockers961, thanks for your feedback.
Btw, what's the step to clear KODI's cache  (just in case I need to it myself).
thanks

**Comment by benaranguren** [comment]
Hey @rockers961 @ricardobothe, Yes, the 2 minute problem usually happens after upgrading but there is code to detect that and it should clear the cached cookie.

On Android, the cookie file should be: /sdcard/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.tfctv/tfctv.cookie

This will vary from device to device. See [Kodi Userdata]( http://kodi.wiki/view/userdata).

As far as concurrent viewing, if you are able to do the same from the official web site then it should be possible.

**Comment by rockers961** [comment]
Appreciate all the efforts @benaranguren. Your TFC addon is working like charm. I am on my early stage of coding and would wanted be of help to our Filipino Kodi users as well. Thanks a lot. @ricardobothe if you're using android, you can simply go to settings>apps>Kodi>clear cache. Thanks.

**Comment by sydwin20** [comment]
Hi there, can anyone point me to the right direction where i can get the 1.7 version. i cant seem to find it. please let me know. Thanks everyone..

**Comment by benaranguren** [comment]
@sydwin20, you can download it from here:
https://github.com/benaranguren/nuodtayo.tv/blob/master/downloads/plugin.video.tfctv/plugin.video.tfctv-0.1.7.zip

**Comment by sydwin20** [comment]
Bud, Thanks for the quick response. your awesome! hey if u need some donation let me know im willing to give a little bit for the hard work. just let me know where to send it. Thanks

**Comment by benaranguren** [comment]
Glad it worked out for you.  I added a link to the downloads folder in the main landing page.

https://github.com/benaranguren/nuodtayo.tv

**Comment by sydwin20** [comment]
Thanks!

**Comment by sydwin20** [comment]
Hey Bud, you know a good add on where i can watch filipino Movies? Pls advice when you get a chance. Thanks

**Comment by sydwin20** [comment]
Hi There, hope your doing well. i updated  my TFC to 1.13 and for some reason it wont play. it will load all the shows and dates but it wont go and play.. do you know any reason? Are u having the same issues? Please let me know. Thanks

**Comment by benaranguren** [comment]
Hi sydwin20, I'm getting the same error too.  The server is coming back with an "Unsupported streaming device error".

**Comment by BigMiggen** [comment]
Me too


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: benaranguren <notifications@github.com> Date: 11/3/17  8:51 AM  (GMT-08:00) To: "benaranguren/nuodtayo.tv" <nuodtayo.tv@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [benaranguren/nuodtayo.tv] error/concurrentviewing (#2) 
Hi sydwin20, I'm getting the same error too.  The server is coming back with an "Unsupported streaming device error".

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/benaranguren/nuodtayo.tv","title":"benaranguren/nuodtayo.tv","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/benaranguren/nuodtayo.tv"}},"updates":{"snippets":[{"icon":"PERSON","message":"@benaranguren in #2: Hi sydwin20, I'm getting the same error too.  The server is coming back with an \"Unsupported streaming device error\".\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/benaranguren/nuodtayo.tv/issues/2#issuecomment-341744104"}}}

**Comment by BigMiggen** [comment]
I think it might have something to do with flash player and android not supporting flash


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: benaranguren <notifications@github.com> Date: 11/3/17  8:51 AM  (GMT-08:00) To: "benaranguren/nuodtayo.tv" <nuodtayo.tv@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [benaranguren/nuodtayo.tv] error/concurrentviewing (#2) 
Hi sydwin20, I'm getting the same error too.  The server is coming back with an "Unsupported streaming device error".

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/benaranguren/nuodtayo.tv","title":"benaranguren/nuodtayo.tv","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/benaranguren/nuodtayo.tv"}},"updates":{"snippets":[{"icon":"PERSON","message":"@benaranguren in #2: Hi sydwin20, I'm getting the same error too.  The server is coming back with an \"Unsupported streaming device error\".\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/benaranguren/nuodtayo.tv/issues/2#issuecomment-341744104"}}}

**Comment by sydwin20** [comment]
Yah That same error.. Thanks

**Comment by BigMiggen** [comment]
It's happening on cmik tfc addon as well


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: sydwin20 <notifications@github.com> Date: 11/3/17  8:55 AM  (GMT-08:00) To: "benaranguren/nuodtayo.tv" <nuodtayo.tv@noreply.github.com> Cc: BigMiggen <Nick99mason@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [benaranguren/nuodtayo.tv] error/concurrentviewing (#2) 
Yah That same error.. Thanks



> On Nov 3, 2017, at 11:51 AM, benaranguren <notifications@github.com> wrote:

> 

> Hi sydwin20, I'm getting the same error too. The server is coming back with an "Unsupported streaming device error".

> 

> —

> You are receiving this because you were mentioned.

> Reply to this email directly, view it on GitHub, or mute the thread.

> 



—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/benaranguren/nuodtayo.tv","title":"benaranguren/nuodtayo.tv","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/benaranguren/nuodtayo.tv"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sydwin20 in #2: Yah That same error.. Thanks\n\n\u003e On Nov 3, 2017, at 11:51 AM, benaranguren \u003cnotifications@github.com\u003e wrote:\n\u003e \n\u003e Hi sydwin20, I'm getting the same error too. The server is coming back with an \"Unsupported streaming device error\".\n\u003e \n\u003e —\n\u003e You are receiving this because you were mentioned.\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\n\u003e \n"}],"action":{"name":"View Issue","url":"https://github.com/benaranguren/nuodtayo.tv/issues/2#issuecomment-341745216"}}}

**Comment by benaranguren** [comment]
Hey guys,  I'm able to get it to work if I set cc_fingerprintid.

**Comment by sydwin20** [comment]
where do u set that up or how?

**Comment by benaranguren** [comment]
I'll push an update where you can enter it in.  This will be unique per user.  I'll post how to find your unique id as well.

**Comment by sydwin20** [comment]
is this mean i wont be able to use it on other box i have?  Oh boy.. thanks Again for your time and hard work..

**Comment by nuodtayo** [comment]
@sydwin20, can you try v0.1.15?  No need to set anything other than your login which should still be set.

**Comment by BigMiggen** [comment]
Seems to work for the first episode you watch. The second sometimes works,sometimes fails. Completely closing and reopening kodi seems to work. I'll test more later. Gotta go to work

**Comment by sydwin20** [comment]
im un able to dwnload it for some reason...

**Comment by sydwin20** [comment]
Yes! its back and Working!!! v1.15.. i played a few episode and its back!!! You guys are Awesome!!!

**Comment by sydwin20** [comment]
same issue again. The TFC error. anyone having the same issue?

**Comment by nuodtayo** [comment]
Same symptoms but different underlying issue.  This time it's complaining about a missing security key.

**Comment by sydwin20** [comment]
yah thats what im getting..

**Comment by nuodtayo** [comment]
Please try v0.1.17

**Comment by sydwin20** [comment]
i tried it.. it works!!! Thanks Again! Hopefully this stay for a while.. lol!! Thanks Again..

**Comment by sydwin20** [comment]
Hey Bud, This TFC IS DOWN AGAIN. Lol! this is crazy. looks like they keep updating there security... wow!!! but thanks again for all your hard work tho eh!

**Comment by BigMiggen** [comment]
Ckik's.71 is working atm. You guys should work together
